apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  labels:
    app: postgres
data:
  POSTGRES_DB: {{ .Values.postgres.pg_db_name }}
  POSTGRES_USER: {{ .Values.postgres.pg_user }}
  POSTGRES_PASSWORD: {{ .Values.postgres.pg_password }}