apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-django
spec:
  selector:
    app: django-app # Deployment App name
  ports:
    - protocol: TCP
      port: {{ .Values.django_app.service.port }}
      targetPort: {{ .Values.django_app.service.port }}
  type: LoadBalancer
