apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-django
spec:
  selector:
    app: django-app # Deployment App name
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
